#!/bin/bash

# Check for inputs
if [ $# -eq 0 ]
  then
    echo "Enter Name of Save Dir"
    exit
fi

# Check for null string
if [ -z "$1" ]
  then
    echo "Enter Name of Save Dir"
    exit
fi

DIR="Results/$1"

mkdir -p $DIR
mkdir -p $DIR/ensi

cp -rf zzz.out $DIR/.
cp -rf xx20.res $DIR/.
cp -rf Displacement.dat $DIR/.
cp -rf gp* $DIR/.
mv *.raw $DIR/ensi/.
mv *.ensi.* $DIR/ensi/.
cp ./ensiFiles/xx20.ensi.geo $DIR/ensi/.
cp ./ensiFiles/xx20.ensi.MATID $DIR/ensi/.
cp ./ensiFiles/xx20.ensi.NDBND $DIR/ensi/.
cp ./ensiFiles/xx20.ensi.NDLDS $DIR/ensi/.
cp ./ensiFiles/xx20.ensi.case $DIR/ensi/. 
